version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443

    volumes:
      - wordpress-data:/var/www/html

  wordpress:
    build: ./requirements/wordpress

    volumes:
      - wordpress-data:/var/www/html

  mariadb: 
    build: ./requirements/mariadb

    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ulayus/data/wordpress

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ulayus/data/mariadb

