version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - '443:443'
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - localhost
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    ports:
      - '9000:9000'
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - localhost
    restart: always

  mariadb: 
    build: ./requirements/mariadb
    ports:
      - '3306:3306'

    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - localhost
    restart: always

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ulayus/data/wordpress'

  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ulayus/data/mariadb'

networks:
  localhost:
    driver: bridge
