CREATE DATABASE IF NOT EXISTS '{MYSQL_DATABASE}';
CREATE USER IF NOT EXISTS {MYSQL_USER}@localhost IDENTIFIED BY '{MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES {MYSQL_USER}@localhost IDENTIFIED BY '{MYSQL_PASSWORD}';
ALTER USER root@localhost IDENTIFIED BY '{MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES; -u root -p{MYSQL_ROOT_PASSWORD}
