#!bin/sh

mysql -e "CREATE DATABASE IF NOT EXISTS \'${MYSQL_DATABASE}\';"
mysql -e "CREATE USER IF NOT EXISTS ${MYSQL_USER}@localhost IDENTIFIED BY \'${MYSQL_PASSWORD}\';"
mysql -e "GRANT ALL PRIVILEGES ${MYSQL_USER}@localhost IDENTIFIED BY \'${MYSQL_PASSWORD}\';"
mysql -e "ALTER USER root@localhost IDENTIFIED BY \'${MYSQL_ROOT_PASSWORD}\';"
mysql -e "FLUSH PRIVILEGES;" -u root -p${MYSQL_ROOT_PASSWORD}

exec mysqld_safe
